### ISSUE TITLE
Add caching to GitHub Actions for speed

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2729]
We have now merged our GitHub Actions config, and it's working well so far - but we're not quite done yet.

- [x] set up secrets in the repo settings, so that GitHub Actions can push releases to GitHub and PyPI
- [x] remove Travis config file and webhooks
- [ ] add caching for performance (@sobolevn volunteered)

**Comment by sobolevn** [comment]
I am looking right now on the `build.sh` script. And it leaves me wondering: how can we cache `TOOL_VIRTUALENV` location? The problem is it does not have a static name and already contains the `hash` part.

I have opened a WIP PR with the initial progress: https://github.com/HypothesisWorks/hypothesis/pull/2730

**Comment by sobolevn** [comment]
Looks like current Travis setup is a bit different. Because that's what it caches:

```yml
cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - $HOME/wheelhouse
        - $HOME/.local
        - vendor/bundle
```

Or I might get the whole `TOOL_VIRTUALENV` idea wrong.
