### ISSUE TITLE
GitHub citation widget

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#3046]
There's a new feature that might be worth trying: https://twitter.com/natfriedman/status/1420122675813441540
Right now `CITATION` is just a text file: https://github.com/HypothesisWorks/hypothesis/blob/master/CITATION

CC @DRMacIver

**Comment by Zac-HD** [comment]
Very happy to see this getting a dedicated UI element!

That said I think we'll want to hold off for a little while; the main thing to cite is actually our JOSS article and so we'll need https://github.com/citation-file-format/ruby-cff/issues/55 to be implemented and supported in the UI.

I also expect some "interesting" interactions between our release automation and Zenodo, since it'll work a little differently now:
https://twitter.com/ZENODO_ORG/status/1420397615355777028

**Comment by Zac-HD** [comment]
While there's now a `preferred-citation` key and this is notionally supported by GitHub, I just can't get  the file to be recognised.  Even when the schema validation passes locally, the website gives me an opaque 'format invalid, try again' message.  Schema documentation: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md

For anyone else who wants to try, just dump the following file into the root of your fork and the sidebar widget will appear.  

```yaml
cff-version: 1.2.0
message: |
  If you use Hypothesis as part of a published research project,
  please cite our paper in the Journal of Open Source Software:

  Text:

  MacIver et al., (2019). Hypothesis: A new approach to property-based testing.
  Journal of Open Source Software, 4(43), 1891, https://doi.org/10.21105/joss.01891

  BibTeX:

  @article{MacIver2019Hypothesis,
    journal = {Journal of Open Source Software},
    doi = {10.21105/joss.01891},
    issn = {2475-9066},
    number = {43},
    publisher = {The Open Journal},
    title = {Hypothesis: A new approach to property-based testing},
    url = {http://dx.doi.org/10.21105/joss.01891},
    volume = {4},
    author = {MacIver, David and Hatfield-Dodds, Zac and Contributors, Many},
    pages = {1891},
    date = {2019-11-21},
    year = {2019},
    month = {11},
    day = {21},
  }

  To reference a particular version of Hypothesis as a software artifact,
  you can use the version-specific DOIs we create for each release under
  https://doi.org/10.5281/zenodo.1412597


preferred-citation:
  title: 'Hypothesis: A new approach to property-based testing'
  date-released: 2019-11-21
  type: article
  doi: 10.21105/joss.01891
  authors:
    - name-particle: R.
      family-names: MacIver
      given-names: David
      orcid: https://orcid.org/0000-0002-8635-3223
      affiliation: Imperial College London
    - family-names: Hatfield-Dodds
      given-names: Zac
      orcid: https://orcid.org/0000-0002-8646-8362
      affiliation: Australian National University
    - name: "many other contributors"

# Citation metadata for the software itself, as required by the CFF spec
doi: 10.5281/zenodo.1412597  # Version-independent DOI for the software archive
title: 'Hypothesis: Property-Based Testing for Python'
repository-code: https://github.com/HypothesisWorks/hypothesis
license: MPL-2.0
authors:
  - name-particle: R.
    family-names: MacIver
    given-names: David
    orcid: https://orcid.org/0000-0002-8635-3223
    affiliation: Imperial College London
  - family-names: Hatfield-Dodds
    given-names: Zac
    orcid: https://orcid.org/0000-0002-8646-8362
    affiliation: Australian National University
  - name: "many other contributors"
```
